"""Adiciona colunas de timestamp em todas as tabelas

Revision ID: f311a927f7da
Revises: 
Create Date: 2025-12-17 02:10:50.570444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f311a927f7da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Disciplina', sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('Disciplina', sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('Disciplina', 'data_criacao')
    op.add_column('Revisao', sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('Revisao', sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('Tema', sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('Tema', sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('Tema', 'data_criacao')
    op.add_column('Usuario', sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('Usuario', sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('Usuario', 'data_cadastro')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Usuario', sa.Column('data_cadastro', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('Usuario', 'atualizado_em')
    op.drop_column('Usuario', 'criado_em')
    op.add_column('Tema', sa.Column('data_criacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('Tema', 'atualizado_em')
    op.drop_column('Tema', 'criado_em')
    op.drop_column('Revisao', 'atualizado_em')
    op.drop_column('Revisao', 'criado_em')
    op.add_column('Disciplina', sa.Column('data_criacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('Disciplina', 'atualizado_em')
    op.drop_column('Disciplina', 'criado_em')
    # ### end Alembic commands ###
